version: "3"

services:
  harvest_db:
    image: postgres
    container_name: harvest_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: artfx
      POSTGRES_DB: harvest
    ports:
      - 5432:5432
    volumes:
      - harvest_db:/var/lib/postgresql/data

  tractor_db:
    image: postgres
    container_name: tractor_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: artfx
      POSTGRES_DB: tractor
    ports:
      - 9876:9876
    volumes:
      - tractor_db:/var/lib/postgresql/data

  harvest_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: harvest_api
    container_name: harvest_api
    ports: 
      - 5000:5000
    depends_on:
      - harvest_postgres
      - tractor_postgres

volumes:
  harvest_db:
  tractor_db:
